---

- hosts: all
  become: yes

  tasks:

  - name: Ensure Apps is installed
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - default-jdk
    - git
    - maven
    - s3cmd

  - name: get s3 settings
    synchronize:
      src: ".s3cfg"
      dest: "/root/.s3cfg"
  - name: Clone app from git
    git:
      repo: https://github.com/Mishiz/devops11.git
      dest: /tmp/boxfuse
  - name: Make WAR file
    shell:
      cmd: mvn -f /tmp/boxfuse/pom.xml package &&  s3cmd put /tmp/boxfuse/target/hello-1.0.war s3://dev1408s/ROOT.war

