---

- hosts: all
  become: yes

  tasks:
  - name: Ensure default-jdk is installed
    apt:
      name: default-jdk
      state: present
  - name: Ensure git is installed
    apt:
      name: git
      state: present
  - name: Ensure maven is installed
    apt:
      name: maven
      state: present
  - name: Ensure s3cmd is present
    apt:
      name: s3cmd
      state: present
  - name: get s3 settings
    synchronize:
      src: ".s3cfg"
      dest: "/root/.s3cfg"
  - name: Clone app from git
    git:
      repo: https://github.com/Mishiz/devops11.git
      dest: /tmp/boxfuse
  - name: Make WAR file
    shell:
      cmd: mvn -f /tmp/boxfuse/pom.xml package &&  s3cmd put /tmp/boxfuse/target/hello-1.0.war s3://dev1408s/ROOT.war

