---

- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: Ensure Apps is installed
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - docker.io
    - s3cmd
    - python3-pip

  - name: get s3 settings
    synchronize:
      src: ".s3cfg"
      dest: "/root/.s3cfg"

  - name: Ensure Pythin-SDK is present
    pip:
      name:
        - docker

  - name: Get Dockerfile
    git:
      repo: https://github.com/Mishiz/devops1701.git
      dest: /tmp/stage1701
  - name: Get WAR file
    shell:
      cmd: s3cmd get s3://dev1408s/ROOT.war /tmp/stage1701/

  - name: Build Docker image
    docker_image:
      name: stage1701
      build:
        path: /tmp/stage1701
        args:
          listen_port: 8080
      source: build
  - name: Docker Image Up
    docker_container:
      name: stage1701deploy
      image: stage1701
      published_ports:
        - "8080:8080"
